[[redirects]]
  from = "/0.109.7/*"
  to = "/0.109.7/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "https://nocodb.com/docs/product-docs/:splat"
  status = 301
  force = true
  conditions = { Host = "docs.nocodb.com" } 